version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${HOST_UID:-0}
        GROUP_ID: ${HOST_GID:-0}
    command: /bin/bash -c "rm tmp/pids/server.pid;
                           bundle install;
                           yarn install;
                           bundle exec rails db:migrate;
                           bundle exec rails s -p 3000 -b 0.0.0.0"
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - bundle-volume:/home/appuser/.local/bundle
    ports:
      - "8080:3000"
    depends_on:
      - db
volumes:
  bundle-volume:
    driver: local
  db-volume:
    driver: local
